### ISSUE TITLE
PickerのPlaceholderがクリックを吸収しUIを操作できない

### ISSUE THREAD

**Issue by mtmtkzm** [topotal/js-sdk#205]
https://user-images.githubusercontent.com/13103139/143571335-f79b0f0a-dd1a-48da-adfc-bca78c802510.mp4

キャプチャにカーソルが入ってなくてわかりにくくてすみません！

**Comment by sawa-zen** [comment]
こちら自分もさっき気づいて https://github.com/topotal/js-sdk/pull/204 で直しました
