### ISSUE TITLE
jsx-quotes が効いてない気がする

### ISSUE THREAD

**Issue by sawa-zen** [topotal/js-sdk#263]

**Comment by sawa-zen** [comment]
@mtmtkzm 
lint の https://eslint.org/docs/rules/jsx-quotes を設定してJSX内はダブルクオーテーションで統一したはずなんですが、いつからか動作していないようです。この件調査して解決してもらえると助かります 🙏🏻

**Comment by sawa-zen** [comment]
なるほど。じゃあコミット前の lint --fix は正常に動いてるってこと？
IDE側だけの問題であれば一旦この件は大丈夫かな

**Comment by mtmtkzm** [comment]
あー、確かにうごいてないですね 🤔  husky がそれですよね?

**Comment by mtmtkzm** [comment]
> yarn lint -- --fix で治るか

こっちは問題なしです！

**Comment by sawa-zen** [comment]
それなら husky も動きそうだけど動いてない？

**Comment by mtmtkzm** [comment]
@sawa-zen Husky自体は、なぎーさんの環境でも動いていますよね？？ 🤔

**Comment by mtmtkzm** [comment]
@sawa-zen 僕のローカルではこうしないと Husky 動かなかったです :pien: 
ただまだ動かなかった原因とかがわからずにいます 🙇 

https://github.com/topotal/js-sdk/pull/290

**Comment by sawa-zen** [comment]
今あらためて main ブランチの最新で確認したら普通に動いた。勘違いだったのかも。
いったんこの件はいいや 🙏🏻
